// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IButtonExampleScss {
  'button-example': string;
}

export const locals: IButtonExampleScss;
export default locals;
