// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IButtonScss {
  'button': string;
  'button--disabled': string;
}

export const locals: IButtonScss;
export default locals;
