// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IDockScss {
  'button': string;
  'button--disabled': string;
}

export const locals: IDockScss;
export default locals;
