// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IPopoverScss {
  'button': string;
  'button--disabled': string;
}

export const locals: IPopoverScss;
export default locals;
